class AppText {
  static Map<String, Map<String, String>> translations = {
    // ENGLISH
    'en': {
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'select_language': 'Select Language',
      'select_role': 'Select Role',
      'farmer': 'Farmer',
      'buyer': 'Buyer',
      'add_product': 'Add Product',
      'my_product': 'My Product',
      'orders_received': 'Orders Received',
      'farmer_dashboard': 'Farmer Dashboard',
      'my_product': 'My Product',
      'buyer_demand': 'Buyer Demand',
      'sell_market': 'Sell Directly To Market',
      'view_bids': 'View Bids',
      'recent_orders': 'Recent Orders',
      'upload_image': 'Upload Product Image',
      'product_name': 'Product Name',
      'price': 'Price',
      'quantity': 'Quantity',
      'product_added': 'Product Added Successfully',
      'fill_fields': 'Please Fill all fields & image',
      'no_products': 'No Products Added',
      'order_received': 'Order received',
      'no_order': 'No order',
      'delivered': 'Delivered',
      'mark_delivered': 'Mark delivered',
      'buyer_demand': 'Buyer demand',
      'no_demand_yet': 'No demand yet',
      'request_from_buyers': 'You see requests from buyers here',
      'select_product_and_price': 'Select product and enter price',
      'select_product': 'Select product',
      'enter_price': 'Enter price',
      'sell_now': 'Sell now',
      'no_market_listing_yet': 'No market listing yet',
      'available_products': 'Available products',
      'no_product_available': 'No product available',
      'kg': 'Kg',
      'ordered_successfully': 'Ordered successfully',
      'buy': 'Buy',
      'browse_product': 'Browse product',
      'added_to_cart': 'Added to cart',
      'no_market_product_available': 'No market product available',
      'base_price': 'Base price',
      'make_bid': 'Make bid',
      'my_bid': 'My bid',
      'buyer_type': 'Buyer type',
      'search': 'Search',
      'my_order': 'My order',
      'my_cart': 'My cart',
      'demand_alert': 'Demand alert',
      'register': 'Register',
      'name': 'Name',
      'email': 'Email',
      'password': 'Password',
      'farmers_register': 'Farmers register',
      'farm_location': 'Farm location',
      'phone_number': 'Phone number',
      'location': 'Location',
      'buyer_registered': 'Buyer registered',
      'address': 'Address',
      'cart_is_empty': 'Cart is empty',
      'order_placed': 'Order placed',
      'place_order': 'Place order',
      'place_bid': 'Place bid',
      'enter_your_bid': 'Enter your bid',
      'submit': 'Submit',
      'accepted': 'Accepted',
      'for_text': 'For',
      'bids_received': 'Bids received',
      'no_bids_yet': 'No bids yet',
      'bid_price': 'Bid price',
      'bid_for': 'Bid for',
      'enter_your_bid_price': 'Enter your bid price',
      'cancel': 'Cancel',
      'bid_placed_successfully': 'Bid placed successfully',
      'market_and_my_bids': 'Market and my bids',
      'household': 'Household',
      'wholesale': 'Wholesale',
      'high_demand': 'High Demand',
      'buyers_ordered_this_product': 'Buyers ordered this product',
      'no_demand_alert': 'No Demand Alert',
      'trending': 'Trending',
      'choose_your_role': 'Choose Your Role',
      'select_role': 'Select Role',
    },

    // KANNADA
    'kn': {
      'choose_your_role': 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'select_role': 'ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'no_demand_alert': 'ಯಾವುದೇ ಬೇಡಿಕೆ ಎಚ್ಚರಿಕೆ ಇಲ್ಲ',
      'trending': 'ಟ್ರೆಂಡಿಂಗ್',
      'high_demand': 'ಹೆಚ್ಚಿನ ಬೇಡಿಕೆ',
      'buyers_ordered_this_product':
          'ಖರೀದಿದಾರರು ಈ ಉತ್ಪನ್ನವನ್ನು ಆರ್ಡರ್ ಮಾಡಿದ್ದಾರೆ',

      'login': 'ಲಾಗಿನ್',
      'email': 'ಇಮೇಲ್',
      'password': 'ಪಾಸ್ವರ್ಡ್',
      'select_language': 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
      'select_role': 'ಪಾತ್ರ ಆಯ್ಕೆ',
      'farmer': 'ರೈತ',
      'buyer': 'ಖರೀದಿದಾರ',
      'add_product': 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
      'my_product': 'ನನ್ನ ಉತ್ಪನ್ನ',
      'orders_received': 'ಆರ್ಡರ್‌ಗಳು',
      'farmer_dashboard': 'ರೈತರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'my_product': 'ನನ್ನ ಉತ್ಪನ್ನ',
      'buyer_demand': 'ಖರೀದಿದಾರರ ಬೇಡಿಕೆ',
      'sell_market': 'ಮಾರುಕಟ್ಟೆಗೆ ಮಾರಾಟ',
      'view_bids': 'ಬಿಡ್‌ಗಳನ್ನು ನೋಡಿ',
      'recent_orders': 'ಇತ್ತೀಚಿನ ಆರ್ಡರ್‌ಗಳು',
      'upload_image': 'ಉತ್ಪನ್ನದ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      'product_name': 'ಉತ್ಪನ್ನದ ಹೆಸರು',
      'price': 'ಬೆಲೆ',
      'quantity': 'ಪ್ರಮಾಣ',
      'product_added': 'ಉತ್ಪನ್ನ ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ',
      'fill_fields': 'ದಯವಿಟ್ಟು ಎಲ್ಲಾ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ',
      'no_products': 'ಯಾವುದೇ ಉತ್ಪನ್ನಗಳನ್ನು ಸೇರಿಸಲಾಗಿಲ್ಲ',

      'order_received': 'ಆರ್ಡರ್ ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
      'no_order': 'ಯಾವುದೇ ಆರ್ಡರ್ ಇಲ್ಲ',
      'delivered': 'ತಲುಪಿಸಲಾಗಿದೆ',
      'mark_delivered': 'ತಲುಪಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ',
      'buyer_demand': 'ಖರೀದಿದಾರರ ಬೇಡಿಕೆ',
      'no_demand_yet': 'ಇನ್ನೂ ಬೇಡಿಕೆ ಇಲ್ಲ',
      'request_from_buyers': 'ಇಲ್ಲಿ ಖರೀದಿದಾರರ ವಿನಂತಿಗಳನ್ನು ನೋಡಬಹುದು',
      'select_product_and_price': 'ಉತ್ಪನ್ನ ಮತ್ತು ಬೆಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'select_product': 'ಉತ್ಪನ್ನ ಆಯ್ಕೆಮಾಡಿ',
      'enter_price': 'ಬೆಲೆ ನಮೂದಿಸಿ',
      'sell_now': 'ಈಗ ಮಾರಾಟ ಮಾಡಿ',
      'no_market_listing_yet': 'ಇನ್ನೂ ಮಾರುಕಟ್ಟೆ ಪಟ್ಟಿ ಇಲ್ಲ',
      'available_products': 'ಲಭ್ಯವಿರುವ ಉತ್ಪನ್ನಗಳು',
      'no_product_available': 'ಯಾವುದೇ ಉತ್ಪನ್ನ ಲಭ್ಯವಿಲ್ಲ',
      'kg': 'ಕೆಜಿ',
      'ordered_successfully': 'ಯಶಸ್ವಿಯಾಗಿ ಆರ್ಡರ್ ಮಾಡಲಾಗಿದೆ',
      'buy': 'ಖರೀದಿ ಮಾಡಿ',
      'browse_product': 'ಉತ್ಪನ್ನಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
      'added_to_cart': 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ',
      'no_market_product_available': 'ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಯಾವುದೇ ಉತ್ಪನ್ನ ಲಭ್ಯವಿಲ್ಲ',
      'base_price': 'ಮೂಲ ಬೆಲೆ',
      'make_bid': 'ಬಿಡ್ ಮಾಡಿ',
      'my_bid': 'ನನ್ನ ಬಿಡ್',
      'buyer_type': 'ಖರೀದಿದಾರರ ಪ್ರಕಾರ',
      'search': 'ಹುಡುಕಿ',
      'my_order': 'ನನ್ನ ಆರ್ಡರ್',
      'my_cart': 'ನನ್ನ ಕಾರ್ಟ್',
      'demand_alert': 'ಬೇಡಿಕೆ ಎಚ್ಚರಿಕೆ',
      'register': 'ನೋಂದಣಿ',
      'name': 'ಹೆಸರು',
      'email': 'ಇಮೇಲ್',
      'password': 'ಪಾಸ್ವರ್ಡ್',
      'farmers_register': 'ರೈತರ ನೋಂದಣಿ',
      'farm_location': 'ಕೃಷಿ ಸ್ಥಳ',
      'phone_number': 'ದೂರವಾಣಿ ಸಂಖ್ಯೆ',
      'location': 'ಸ್ಥಳ',
      'buyer_registered': 'ಖರೀದಿದಾರ ನೋಂದಾಯಿಸಲಾಗಿದೆ',
      'address': 'ವಿಳಾಸ',
      'cart_is_empty': 'ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ',
      'order_placed': 'ಆರ್ಡರ್ ಮಾಡಲಾಗಿದೆ',
      'place_order': 'ಆರ್ಡರ್ ಮಾಡಿ',
      'place_bid': 'ಬಿಡ್ ಇಡಿ',
      'enter_your_bid': 'ನಿಮ್ಮ ಬಿಡ್ ನಮೂದಿಸಿ',
      'submit': 'ಸಲ್ಲಿಸಿ',
      'accepted': 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
      'for_text': 'ಗಾಗಿ',
      'bids_received': 'ಸ್ವೀಕರಿಸಿದ ಬಿಡ್‌ಗಳು',
      'no_bids_yet': 'ಇನ್ನೂ ಯಾವುದೇ ಬಿಡ್ ಇಲ್ಲ',
      'bid_price': 'ಬಿಡ್ ಬೆಲೆ',
      'bid_for': 'ಇದಕ್ಕಾಗಿ ಬಿಡ್',
      'enter_your_bid_price': 'ನಿಮ್ಮ ಬಿಡ್ ಬೆಲೆ ನಮೂದಿಸಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'bid_placed_successfully': 'ಬಿಡ್ ಯಶಸ್ವಿಯಾಗಿ ಇಡಲಾಗಿದೆ',
      'market_and_my_bids': 'ಮಾರುಕಟ್ಟೆ ಮತ್ತು ನನ್ನ ಬಿಡ್‌ಗಳು',
      'household': 'ಗೃಹ ಬಳಕೆ',
      'wholesale': 'ಸಗಟು',
    },

    // HINDI
    'hi': {
      'choose_your_role': 'अपनी भूमिका चुनें',
      'select_role': 'भूमिका चुनें',
      'high_demand': 'अधिक मांग',
      'buyers_ordered_this_product': 'खरीदारों ने इस उत्पाद का ऑर्डर किया',
      'no_demand_alert': 'कोई मांग अलर्ट नहीं',
      'trending': 'ट्रेंडिंग',
      'login': 'लॉगिन',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'select_language': 'भाषा चुनें',
      'select_role': 'भूमिका चुनें',
      'farmer': 'किसान',
      'buyer': 'खरीदार',
      'add_product': 'उत्पाद जोड़ें',
      'my_product': 'मेरे उत्पाद',
      'orders_received': 'ऑर्डर प्राप्त हुए',
      'farmer_dashboard': 'किसान डैशबोर्ड',
      'my_product': 'मेरे उत्पाद',
      'buyer_demand': 'खरीदार की मांग',
      'sell_market': 'सीधे बाजार में बेचें',
      'view_bids': 'बोली देखें',
      'recent_orders': 'हाल के ऑर्डर',
      'upload_image': 'उत्पाद की छवि अपलोड करें',
      'product_name': 'उत्पाद का नाम',
      'price': 'कीमत',
      'quantity': 'मात्रा',
      'product_added': 'उत्पाद सफलतापूर्वक जोड़ा गया',
      'fill_fields': 'कृपया सभी विवरण भरें',
      'no_products': 'कोई उत्पाद नहीं जोड़ा गया',
      'order_received': 'ऑर्डर प्राप्त हुआ',
      'no_order': 'कोई ऑर्डर नहीं',
      'delivered': 'डिलीवर किया गया',
      'mark_delivered': 'डिलीवर के रूप में चिन्हित करें',
      'buyer_demand': 'खरीदार की मांग',
      'no_demand_yet': 'अभी तक कोई मांग नहीं',
      'request_from_buyers': 'यहाँ खरीदारों के अनुरोध दिखाई देंगे',
      'select_product_and_price': 'उत्पाद और कीमत चुनें',
      'select_product': 'उत्पाद चुनें',
      'enter_price': 'कीमत दर्ज करें',
      'sell_now': 'अभी बेचें',
      'no_market_listing_yet': 'अभी तक कोई मार्केट लिस्टिंग नहीं',
      'available_products': 'उपलब्ध उत्पाद',
      'no_product_available': 'कोई उत्पाद उपलब्ध नहीं',
      'kg': 'किलो',
      'ordered_successfully': 'सफलतापूर्वक ऑर्डर किया गया',
      'buy': 'खरीदें',
      'browse_product': 'उत्पाद देखें',
      'added_to_cart': 'कार्ट में जोड़ा गया',
      'no_market_product_available': 'कोई मार्केट उत्पाद उपलब्ध नहीं',
      'base_price': 'मूल कीमत',
      'make_bid': 'बोली लगाएं',
      'my_bid': 'मेरी बोली',
      'buyer_type': 'खरीदार प्रकार',
      'search': 'खोजें',
      'my_order': 'मेरा ऑर्डर',
      'my_cart': 'मेरा कार्ट',
      'demand_alert': 'मांग अलर्ट',
      'register': 'रजिस्टर',
      'name': 'नाम',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'farmers_register': 'किसान पंजीकरण',
      'farm_location': 'खेत का स्थान',
      'phone_number': 'फोन नंबर',
      'location': 'स्थान',
      'buyer_registered': 'खरीदार पंजीकृत',
      'address': 'पता',
      'cart_is_empty': 'कार्ट खाली है',
      'order_placed': 'ऑर्डर किया गया',
      'place_order': 'ऑर्डर करें',
      'place_bid': 'बोली लगाएं',
      'enter_your_bid': 'अपनी बोली दर्ज करें',
      'submit': 'सबमिट',
      'accepted': 'स्वीकृत',
      'for_text': 'के लिए',
      'bids_received': 'प्राप्त बोलियां',
      'no_bids_yet': 'अभी तक कोई बोली नहीं',
      'bid_price': 'बोली कीमत',
      'bid_for': 'के लिए बोली',
      'enter_your_bid_price': 'अपनी बोली कीमत दर्ज करें',
      'cancel': 'रद्द करें',
      'bid_placed_successfully': 'बोली सफलतापूर्वक लगाई गई',
      'market_and_my_bids': 'मार्केट और मेरी बोलियां',
      'household': 'घरेलू',
      'wholesale': 'थोक',
    },

    // TELUGU
    'te': {
      'choose_your_role': 'మీ పాత్రను ఎంచుకోండి',
      'select_role': 'పాత్రను ఎంచుకోండి',
      'no_demand_alert': 'డిమాండ్ అలర్ట్ లేదు',
      'trending': 'ట్రెండింగ్',
      'high_demand': 'అధిక డిమాండ్',
      'buyers_ordered_this_product':
          'కొనుగోలుదారులు ఈ ఉత్పత్తిని ఆర్డర్ చేశారు',

      'login': 'లాగిన్',
      'email': 'ఇమెయిల్',
      'password': 'పాస్‌వర్డ్',
      'select_language': 'భాషను ఎంచుకోండి',
      'select_role': 'పాత్రను ఎంచుకోండి',
      'farmer': 'రైతు',
      'buyer': 'కొనుగోలుదారు',
      'add_product': 'ఉత్పత్తిని జోడించండి',
      'my_product': 'నా ఉత్పత్తులు',
      'orders_received': 'ఆర్డర్లు',
      'farmer_dashboard': 'రైతు డ్యాష్‌బోర్డ్',
      'my_product': 'నా ఉత్పత్తులు',
      'buyer_demand': 'కొనుగోలుదారుల డిమాండ్',
      'sell_market': 'మార్కెట్‌కు నేరుగా అమ్మండి',
      'view_bids': 'బిడ్‌లను చూడండి',
      'recent_orders': 'ఇటీవలి ఆర్డర్లు',
      'upload_image': 'ఉత్పత్తి చిత్రాన్ని అప్‌లోడ్ చేయండి',
      'product_name': 'ఉత్పత్తి పేరు',
      'price': 'ధర',
      'quantity': 'పరిమాణం',
      'product_added': 'ఉత్పత్తి విజయవంతంగా జోడించబడింది',
      'fill_fields': 'దయచేసి అన్ని వివరాలను నమోదు చేయండి',
      'no_products': 'ఉత్పత్తులు జోడించబడలేదు',
      'order_received': 'ఆర్డర్ స్వీకరించబడింది',
      'no_order': 'ఆర్డర్ లేదు',
      'delivered': 'డెలివర్ చేయబడింది',
      'mark_delivered': 'డెలివర్ అయినట్లు గుర్తించండి',
      'buyer_demand': 'కొనుగోలుదారుల డిమాండ్',
      'no_demand_yet': 'ఇంకా డిమాండ్ లేదు',
      'request_from_buyers': 'ఇక్కడ కొనుగోలుదారుల అభ్యర్థనలు కనిపిస్తాయి',
      'select_product_and_price': 'ఉత్పత్తి మరియు ధరను ఎంచుకోండి',
      'select_product': 'ఉత్పత్తిని ఎంచుకోండి',
      'enter_price': 'ధర నమోదు చేయండి',
      'sell_now': 'ఇప్పుడే అమ్మండి',
      'no_market_listing_yet': 'ఇంకా మార్కెట్ జాబితా లేదు',
      'available_products': 'అందుబాటులో ఉన్న ఉత్పత్తులు',
      'no_product_available': 'ఉత్పత్తులు అందుబాటులో లేవు',
      'kg': 'కిలో',
      'ordered_successfully': 'విజయవంతంగా ఆర్డర్ చేయబడింది',
      'buy': 'కొనండి',
      'browse_product': 'ఉత్పత్తులను చూడండి',
      'added_to_cart': 'కార్ట్‌లో చేర్చబడింది',
      'no_market_product_available': 'మార్కెట్‌లో ఉత్పత్తులు లేవు',
      'base_price': 'మూల ధర',
      'make_bid': 'బిడ్ పెట్టండి',
      'my_bid': 'నా బిడ్',
      'buyer_type': 'కొనుగోలుదారు రకం',
      'search': 'శోధించండి',
      'my_order': 'నా ఆర్డర్',
      'my_cart': 'నా కార్ట్',
      'demand_alert': 'డిమాండ్ అలర్ట్',
      'register': 'నమోదు',
      'name': 'పేరు',
      'email': 'ఈమెయిల్',
      'password': 'పాస్‌వర్డ్',
      'farmers_register': 'రైతుల నమోదు',
      'farm_location': 'వ్యవసాయ స్థలం',
      'phone_number': 'ఫోన్ నంబర్',
      'location': 'స్థానం',
      'buyer_registered': 'కొనుగోలుదారు నమోదు అయ్యారు',
      'address': 'చిరునామా',
      'cart_is_empty': 'కార్ట్ ఖాళీగా ఉంది',
      'order_placed': 'ఆర్డర్ చేయబడింది',
      'place_order': 'ఆర్డర్ చేయండి',
      'place_bid': 'బిడ్ పెట్టండి',
      'enter_your_bid': 'మీ బిడ్ నమోదు చేయండి',
      'submit': 'సమర్పించండి',
      'accepted': 'ఆమోదించబడింది',
      'for_text': 'కొరకు',
      'bids_received': 'అందుకున్న బిడ్‌లు',
      'no_bids_yet': 'ఇంకా బిడ్‌లు లేవు',
      'bid_price': 'బిడ్ ధర',
      'bid_for': 'దీనికి బిడ్',
      'enter_your_bid_price': 'మీ బిడ్ ధర నమోదు చేయండి',
      'cancel': 'రద్దు చేయండి',
      'bid_placed_successfully': 'బిడ్ విజయవంతంగా పెట్టబడింది',
      'market_and_my_bids': 'మార్కెట్ మరియు నా బిడ్‌లు',
      'household': 'గృహ వినియోగం',
      'wholesale': 'టోకు',
    },

    // TAMIL
    'ta': {
      'high_demand': 'அதிக தேவை',
      'buyers_ordered_this_product':
          'வாங்குபவர்கள் இந்த பொருளை ஆர்டர் செய்துள்ளனர்',
      'login': 'உள்நுழை',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'select_language': 'மொழியை தேர்ந்தெடுக்கவும்',
      'select_role': 'பாத்திரத்தை தேர்ந்தெடுக்கவும்',
      'farmer': 'விவசாயி',
      'buyer': 'வாங்குபவர்',
      'add_product': 'பொருள் சேர்க்கவும்',
      'my_product': 'என் பொருட்கள்',
      'orders_received': 'ஆர்டர்கள்',
      'farmer_dashboard': 'விவசாயி டாஷ்போர்டு',
      'my_product': 'என் பொருட்கள்',
      'buyer_demand': 'வாங்குபவர் கோரிக்கை',
      'sell_market': 'சந்தைக்கு நேரடியாக விற்கவும்',
      'view_bids': 'பிட்களை பார்க்கவும்',
      'recent_orders': 'சமீபத்திய ஆர்டர்கள்',
      'upload_image': 'பொருள் படத்தை பதிவேற்றவும்',
      'product_name': 'பொருளின் பெயர்',
      'price': 'விலை',
      'quantity': 'அளவு',
      'product_added': 'பொருள் வெற்றிகரமாக சேர்க்கப்பட்டது',
      'fill_fields': 'அனைத்து விவரங்களையும் நிரப்பவும்',
      'no_products': 'பொருட்கள் சேர்க்கப்படவில்லை',
      'order_received': 'ஆர்டர் பெறப்பட்டது',
      'no_order': 'ஆர்டர் இல்லை',
      'delivered': 'வழங்கப்பட்டது',
      'mark_delivered': 'வழங்கப்பட்டதாக குறிக்கவும்',
      'buyer_demand': 'வாங்குபவர் தேவைகள்',
      'no_demand_yet': 'இன்னும் தேவைகள் இல்லை',
      'request_from_buyers': 'இங்கே வாங்குபவர்களின் கோரிக்கைகள் காணப்படும்',
      'select_product_and_price': 'பொருள் மற்றும் விலையை தேர்வு செய்யவும்',
      'select_product': 'பொருளை தேர்வு செய்யவும்',
      'enter_price': 'விலையை உள்ளிடவும்',
      'sell_now': 'இப்போது விற்கவும்',
      'no_market_listing_yet': 'இன்னும் சந்தை பட்டியல் இல்லை',
      'available_products': 'கிடைக்கும் பொருட்கள்',
      'no_product_available': 'பொருள் எதுவும் கிடைக்கவில்லை',
      'kg': 'கிலோ',
      'ordered_successfully': 'வெற்றிகரமாக ஆர்டர் செய்யப்பட்டது',
      'buy': 'வாங்கவும்',
      'browse_product': 'பொருட்களை பார்க்கவும்',
      'added_to_cart': 'கார்டில் சேர்க்கப்பட்டது',
      'no_market_product_available': 'சந்தையில் பொருள் இல்லை',
      'base_price': 'அடிப்படை விலை',
      'make_bid': 'பிட் இடவும்',
      'my_bid': 'என் பிட்',
      'buyer_type': 'வாங்குபவர் வகை',
      'search': 'தேடல்',
      'my_order': 'என் ஆர்டர்கள்',
      'my_cart': 'என் கார்ட்',
      'demand_alert': 'தேவை எச்சரிக்கை',
      'register': 'பதிவு செய்யவும்',
      'name': 'பெயர்',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'farmers_register': 'விவசாயிகள் பதிவு',
      'farm_location': 'பண்ணை இடம்',
      'phone_number': 'தொலைபேசி எண்',
      'location': 'இடம்',
      'buyer_registered': 'வாங்குபவர் பதிவு செய்யப்பட்டார்',
      'address': 'முகவரி',
      'cart_is_empty': 'கார்ட் காலியாக உள்ளது',
      'order_placed': 'ஆர்டர் செய்யப்பட்டது',
      'place_order': 'ஆர்டர் செய்யவும்',
      'place_bid': 'பிட் இடவும்',
      'enter_your_bid': 'உங்கள் பிட் உள்ளிடவும்',
      'submit': 'சமர்ப்பிக்கவும்',
      'accepted': 'ஏற்கப்பட்டது',
      'for_text': 'க்காக',
      'bids_received': 'பெறப்பட்ட பிட்கள்',
      'no_bids_yet': 'இன்னும் பிட்கள் இல்லை',
      'bid_price': 'பிட் விலை',
      'bid_for': 'இதற்கான பிட்',
      'enter_your_bid_price': 'உங்கள் பிட் விலையை உள்ளிடவும்',
      'cancel': 'ரத்து செய்யவும்',
      'bid_placed_successfully': 'பிட் வெற்றிகரமாக இடப்பட்டது',
      'market_and_my_bids': 'மார்க்கெட் மற்றும் என் பிட்கள்',
      'household': 'வீட்டு பயன்பாடு',
      'wholesale': 'மொத்த விற்பனை',
      'no_demand_alert': 'தேவை எச்சரிக்கை இல்லை',
      'trending': 'டிரெண்டிங்',
      'choose_your_role': 'உங்கள் பாத்திரத்தை தேர்வு செய்யவும்',
      'select_role': 'பாத்திரத்தை தேர்வு செய்யவும்',
    },
  };
}
